# use sudo permission
sudo: required
services:
  - docker

before_install:
  - docker build -t lgxkevin/docker-with-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lgxkevin/docker-with-react npm run test